### PR TITLE
docs: Added github repo to orb description

### PR DESCRIPTION
**Pull request by piyush-insider**
Added Github repo to Orb description
Resolves : #356

### CODE REVIEW

**Comment by piyush-insider** [comment]
@djones Can I please request your review on this?

**Comment by djones** [comment]
Hi @piyush-insider, where is this documented with CircleCI? I don't see it in the configuration reference https://circleci.com/docs/2.0/configuration-reference/

**Comment by piyush-insider** [comment]
Hi @djones It's listed as a best practice for metadata in the CircleCi documentation.
You can find it here.
https://circleci.com/docs/2.0/orbs-best-practices/#metadata

**Comment by djones** [comment]
ok so it's part of the description field but this PR adds it as a YAML key on the next line, which ultimately won't get included in the description and actually causes a YAML validation error.

You can use `circleci orb validate` to check the configuration is valid. The validation comes back like this at the moment:

```bash
~/Code/percy-agent/.circleci(master ✗) circleci orb validate ./orb.yml
Error: Unable to parse YAML
mapping values are not allowed here
 in 'string', line 5, column 7:
      Repo: https://github.com/percy/percy ...
          ^
```

How about we change it to be something like this, using the `>` operator to get multiple lines working in the description.

```yaml
version: "2.1"
description: >
  Workflow for running Percy builds in parallel. Your token will be read from $PERCY_TOKEN by default, but this
  can be overridden using the `percy_token` parameter. Source code: https://github.com/percy/percy-agent

examples:
  finalize_all_percy_builds:
# ... rest of file
```

**Comment by piyush-insider** [comment]
Hey, @djones thanks for pointing out the missing operator! I have updated the description accordingly.

**Pull request merged**
